version: '3'
services: 
  car-service:
    build: backend/home
    image: car-serevice-v1
    ports:
      - "9001:9001"
  home-service:
    build: backend/home
    image: home-service-v1
    ports: 
      - "9000:9000"
  font-end:
    build: fontend
    image: fontent-v1
    ports: 
      - "3000:80"