version: '2'
services: 
  frontend:
      build: ./fontend
      image: frontend:v1
      ports: 
        - 4200:80
      
  backend1:
      build: ./backend/car
      image: backend1
      ports:
        - 9001:9001
  backend2:
      build: ./backend/home
      image: backend2
      ports:
        - 9000:9000